Prevent draft posts from being federated when deleted
Automattic/wordpress-activitypub pull request #1041
Opened 2024-12-04 17:39 UTC by obenland

Fixes #1030.

## Proposed changes:

* Added status transition handling in `schedule_post_activity()` to prevent federation of draft posts.
* Added test coverage for post status transitions.

### Other information:

- [x] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Create a draft post
* Create a published post
* Select both posts in the admin list view
* Bulk delete them
* Verify that:
  * The published post sends a Delete activity to followers
  * The draft post is deleted without federation

2024-12-04 17:46 UTC, pfefferle commented
We do not really know the state, a draft had before the delete. A post could have been published, migrated to a draft and then deleted. In this case we have to send a `Delete`.

2024-12-04 17:49 UTC, obenland commented
> migrated to a draft

Can you tell me more about that? Something that skips `transition_post_status()`?

2024-12-04 17:50 UTC, pfefferle requested changes

2024-12-04 17:50 UTC, pfefferle commented on includes/class-scheduler.php
> +				$type = ( 'publish' === $old_status ) ? 'Delete' : false;
the check has to be if the post has the `activitypub_status` federated instead of checking the previous one: https://github.com/Automattic/wordpress-activitypub/blob/6c18433965d291459cc00ea885808ffc3bc8dea0/includes/class-activity-dispatcher.php#L194C3-L194C22

https://github.com/Automattic/wordpress-activitypub/blob/6c18433965d291459cc00ea885808ffc3bc8dea0/includes/functions.php#L898

2024-12-04 17:52 UTC, pfefferle commented
@obenland if a post status is changed from "publish" to "draft", it will not deleted from the fediverse. If the user then deletes the draft, has the former status "draft" and will not be send a `Delete` to the fediverse.

In this case the fediverse will keep the draft post for ever.

2024-12-04 20:27 UTC, obenland commented
That makes sense, thanks. Sounds like the switch to the federated check should cover that?

2024-12-05 12:43 UTC, pfefferle commented
it will set when the post/comment will be federated, so I would assume yes :)

2024-12-05 14:32 UTC, pfefferle approved these changes

2024-12-05 15:10 UTC, merged