Init new custom mailer class
Automattic/wordpress-activitypub pull request #1068
Opened 2024-12-10 16:13 UTC by pfefferle

I forgot to load the mailer 🫣

And added some line breaks

<img width="760" alt="Screenshot 2024-12-10 at 17 09 57" src="https://github.com/user-attachments/assets/98aef6ac-8a49-4190-889b-b09f4ea9d44d">
<img width="760" alt="Screenshot 2024-12-10 at 17 10 03" src="https://github.com/user-attachments/assets/9e6bf735-2e20-44eb-a566-c1c35af8980d">
<img width="760" alt="Screenshot 2024-12-10 at 17 10 08" src="https://github.com/user-attachments/assets/67a9047d-fbfd-4bcc-8eb2-daf4d6123fa8">
<img width="760" alt="Screenshot 2024-12-10 at 17 10 12" src="https://github.com/user-attachments/assets/b575a06f-927b-43ab-8653-2fb7da32607b">

2024-12-10 17:51 UTC, obenland requested changes

2024-12-10 17:51 UTC, obenland commented on includes/class-mailer.php
>  		/* translators: %1$s: Blog name, %2$s: Post title */
```suggestion
		/* translators: 1: Blog name, 2: Like or Repost, 3: Post title */
```

2024-12-10 17:51 UTC, obenland commented on includes/class-mailer.php
>  		$message .= \sprintf( \__( 'URL: %s', 'activitypub' ), $actor['url'] ) . "\r\n\r\n";
```suggestion
		$message .= \sprintf( \__( 'URL: %s', 'activitypub' ), esc_url( $actor['url'] ) ) . "\r\n\r\n";
```

2024-12-10 17:51 UTC, obenland commented on includes/class-mailer.php
>  		$message .= \sprintf( \__( 'URL: %s', 'activitypub' ), $actor['url'] ) . "\r\n\r\n";
Everything in `$message` should be escaped, actually. I didn't check that earlier.

2024-12-10 17:51 UTC, obenland commented on includes/class-mailer.php
> +		$message = \sprintf( \__( 'New Direct-Message: %2$s', 'activitypub' ), get_option( 'blogname' ), \wp_strip_all_tags( $activity['object']['content'], 'allowed_comment_html' ) ) . "\r\n\r\n";
```suggestion
		/* translators: 1: Blog name, 2 Actor name */
		$subject = \sprintf( \__( '[%1$s] Direct Message from: %2$s', 'activitypub' ), get_option( 'blogname' ), $actor['name'] );
		/* translators: 1: Blog name, 2: Actor name */
		$message = \sprintf( \__( 'New Direct Message: %2$s', 'activitypub' ), get_option( 'blogname' ), \wp_strip_all_tags( $activity['object']['content'], 'allowed_comment_html' ) ) . "\r\n\r\n";
```

2024-12-10 17:51 UTC, obenland commented on includes/class-mailer.php
> +		$message .= \sprintf( \__( 'URL: %s', 'activitypub' ), $actor['url'] ) . "\r\n\r\n";
same here with escaping

2024-12-10 21:30 UTC, obenland approved these changes, later dismissed

2024-12-11 10:37 UTC, pfefferle commented on includes/class-mailer.php
>  		\wp_mail( $email, $subject, $message );
Should we support HTML mails for direct messages?

```suggestion
		$message = \sprintf( \esc_html__( 'New Direct Message: %2$s', 'activitypub' ), \esc_html( get_option( 'blogname' ) ), \wp_kses( $activity['object']['content'] ) ) . "<br/><br/>";
		/* translators: Actor name */
		$message .= \sprintf( \esc_html__( 'From: %s', 'activitypub' ), \esc_html( $actor['name'] ) ) . "<br/>";
		/* translators: Actor URL */
		$message .= \sprintf( \esc_html__( 'URL: %s', 'activitypub' ), \esc_url( $actor['url'] ) ) . "<br/><br/>";

		\wp_mail( $email, $subject, $message, array( 'Content-Type: text/html' ) );
```

2024-12-11 10:39 UTC, pfefferle commented on includes/class-mailer.php
>  		\wp_mail( $email, $subject, $message );
this is not working code, just to show how it might be possible!

2024-12-11 14:01 UTC, obenland commented on includes/class-mailer.php
>  		\wp_mail( $email, $subject, $message );
I think it's fine as is for now.

2024-12-11 14:02 UTC, obenland approved these changes

2024-12-11 14:23 UTC, merged