Fix link regex
Automattic/wordpress-activitypub pull request #922
Opened 2024-10-02 17:29 UTC by mattwiebe

We are getting a bunch of errors like this on wpcom:

```
Warning: Undefined array key "host" in /wp-content/plugins/activitypub/dev/includes/class-link.php on line 84
```

This is because the previous regex was matching a string like `www foo` when it shouldn't be. I don't understand why the previous negated character class didn't work, but using the `\S` class is equivalent to `^\s`. I simplified the `https?` match a bit while I was in there.

## Proposed changes:
* improve `ACTIVITYPUB_URL_REGEXP` 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?

## Testing instructions:

* Go to '..'
*

2024-10-02 17:29 UTC, mattwiebe commented on includes/class-link.php
>  			return $result[0];
This might not be needed but seemed like useful defensiveness.

2024-10-03 11:44 UTC, pfefferle requested changes
@mattwiebe can you add the false positives to the test case?

2024-10-04 01:48 UTC, mattwiebe commented
> @mattwiebe can you add the false positives to the test case?

Will do! Having a little trouble with the tests (again) but I'll circle back with fresh energy tomorrow

2024-10-07 07:23 UTC, pfefferle approved these changes

2024-10-07 11:25 UTC, merged